### ISSUE TITLE
Garden Upgrades showing twice

### ISSUE THREAD

**Issue by Tithonius** [Chakaa/cookie-garden-helper-reloaded#11]
So, I have a few mods installed, (Including horticookie, but I have disabled it and checked, and the issue still persists) but I see the Garden upgrades twice. Would love to know if you see a conflict, or if this is a bug that can be fixed. Thanks for the help!

My modlist is as follows:
![skQDApZ](https://user-images.githubusercontent.com/20254673/135742738-c2cdbc43-472e-4a2d-bd9e-03e8a0b2f34a.png)

And a picture of the issue here:
![8jMW2Pn](https://user-images.githubusercontent.com/20254673/135742762-3d7491d5-fb3d-41c7-834f-a6977c13ec76.jpg)

**Comment by Chakaa** [comment]
Hi,
Indeed, it might be a side effect to all those mods, and how I've implemented the mod.
Do you mind testing the version I've attached?
[CookieGardenHelper-reloaded.zip](https://github.com/Chakaa/cookie-garden-helper-reloaded/files/7272840/CookieGardenHelper-reloaded.zip)

**Comment by Tithonius** [comment]
Same issue unfortunately :/

**Comment by Tithonius** [comment]
disabling all but these 3 mods and i still have the problem

![](https://i.imgur.com/0tv6oPI.png)

**Comment by Tithonius** [comment]
so its either with the achievement enabler, or CCSE

**Comment by Chakaa** [comment]
Ok, I've installed CCSE, and was able to reproduce your issue.
Let me push a new version to cover that issue.

**Comment by Chakaa** [comment]
Please try out the latest version 1.4.6. It should cover your situation.

**Comment by Tithonius** [comment]
Fixed!

![](https://i.imgur.com/aJSifNe.jpeg)

Thanks

**Comment by Chakaa** [comment]
Glad to hear that, thank you for the report.
